# Generated by Django 5.2.8 on 2025-11-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='originals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropped_image', models.ImageField(upload_to='crops/')),
                ('label', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='presc.prescriptionimage')),
            ],
        ),
    ]
