# Generated by Django 5.2.8 on 2025-11-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croplabel',
            name='pan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croplabel',
            name='rotate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='croplabel',
            name='zoom',
            field=models.FloatField(default=1),
        ),
    ]
